export const CASE_TEMPLATES = {
  consumer: {
    name: 'CONSUMER_PETITION',
    description: 'Statutory complaint under Consumer Protection Act, 2019',
    steps: [
      {
        id: 1,
        label: 'Archive Essential Documentation',
        description: 'Collect bills, receipts, correspondence, product photos',
        completed: false,
      },
      {
        id: 2,
        label: 'Serve Statutory Notice',
        description: 'Send legal notice to opposite party under Section 72 of CPA 2019',
        completed: false,
        expectedDays: 30,
      },
      {
        id: 3,
        label: 'Draft Formal Petition',
        description: 'Prepare complaint with facts, relief sought, and documents',
        completed: false,
      },
      {
        id: 4,
        label: 'File with Competent Commission',
        description: 'File at District/State/National Commission based on pecunary value',
        completed: false,
      },
      {
        id: 5,
        label: 'Pay Court Fee',
        description: 'Pay nominal fee (Rs. 100-500 depending on value)',
        completed: false,
      },
      {
        id: 6,
        label: 'First Hearing - Admission',
        description: 'Court examines if complaint is admissible',
        completed: false,
      },
      {
        id: 7,
        label: 'Notice to Opposite Party',
        description: 'Court issues notice to opposite party',
        completed: false,
      },
      {
        id: 8,
        label: 'Evidence & Arguments',
        description: 'Submit evidence and present arguments',
        completed: false,
      },
      {
        id: 9,
        label: 'Final Order',
        description: 'Receive compensation/refund order',
        completed: false,
      },
    ],
  },
  criminal: {
    name: 'CRIMINAL_PROCEEDING',
    description: 'Procedural lifecycle under BNS/BNSS framework',
    steps: [
      {
        id: 1,
        label: 'FIR_REGISTRATION',
        description: 'Formal First Information Report registration via physical or digital portal',
        completed: false,
      },
      {
        id: 2,
        label: 'INVESTIGATION_PHASE',
        description: 'Executive investigation and evidentiary collection by authorities',
        completed: false,
      },
      {
        id: 3,
        label: 'CHARGESHEET_SUBMISSION',
        description: 'Formal filing of chargesheet under BNSS Section 193',
        completed: false,
      },
      {
        id: 4,
        label: 'JUDICIAL_PRODUCTION',
        description: 'Accused produced before competent Magistrate for remand',
        completed: false,
      },
      {
        id: 5,
        label: 'BAIL_ADJUDICATION',
        description: 'Submission and adjudication of regular/anticipatory bail petitions',
        completed: false,
      },
      {
        id: 6,
        label: 'FRAMING_OF_CHARGES',
        description: 'Judicial determination of charges under relevant statutory sections',
        completed: false,
      },
      {
        id: 7,
        label: 'PROSECUTION_EVIDENCE',
        description: 'Submission of prosecution witnesses and verified evidence',
        completed: false,
      },
      {
        id: 8,
        label: 'CROSS_EXAMINATION',
        description: 'Procedural cross-examination of prosecution witnesses',
        completed: false,
      },
      {
        id: 9,
        label: 'DEFENSE_EVIDENCE',
        description: 'Presentation of defense witnesses and counter-evidence',
        completed: false,
      },
      {
        id: 10,
        label: 'FINAL_ARGUMENTS',
        description: 'Procedural final arguments by both side councils',
        completed: false,
      },
      { id: 11, label: 'FINAL_ADJUDICATION', description: 'Judicial pronouncement of verdict', completed: false },
      {
        id: 12,
        label: 'SENTENCING_PROTOCOL',
        description: 'Pronouncement of sentence or initiation of appellate proceedings',
        completed: false,
      },
    ],
  },
  civil: {
    name: 'CIVIL_SUIT_FILING',
    description: 'Procedural lifecycle for statutory civil litigation',
    steps: [
      {
        id: 1,
        label: 'DRAFT_PLAINT',
        description: 'Preparation of formal plaint specifying cause of action and relief sought',
        completed: false,
      },
      {
        id: 2,
        label: 'FILING_OF_SUIT',
        description: 'Formal submission of suit at the competent civil court of jurisdiction',
        completed: false,
      },
      {
        id: 3,
        label: 'STATUTORY_COURT_FEE',
        description: 'Payment of ad valorem court fees based on relief valuation',
        completed: false,
      },
      {
        id: 4,
        label: 'ADMISSION_&_SUMMONS',
        description: 'Judicial admission of suit and issuance of formal summons',
        completed: false,
      },
      {
        id: 5,
        label: 'SERVICE_OF_SUMMONS',
        description: 'Verification of summons service to the defendant party',
        completed: false,
      },
      {
        id: 6,
        label: 'WRITTEN_STATEMENT',
        description: 'Filing of formal written statement by the defendant within statutory limits',
        completed: false,
      },
      {
        id: 7,
        label: 'FRAMING_OF_ISSUES',
        description: 'Judicial determination and framing of issues for formal trial',
        completed: false,
      },
      {
        id: 8,
        label: 'PLAINTIFF_EVIDENCE',
        description: 'Submission of evidence by plaintiff (Witnesses & Documents)',
        completed: false,
      },
      {
        id: 9,
        label: 'DEFENDANT_EVIDENCE',
        description: 'Submission of evidence by defendant party',
        completed: false,
      },
      {
        id: 10,
        label: 'FINAL_ARGUMENTS',
        description: 'Procedural final arguments based on framed trial issues',
        completed: false,
      },
      { id: 11, label: 'FINAL_ADJUDICATION', description: 'Judicial pronouncement of judgment', completed: false },
      {
        id: 12,
        label: 'EXECUTION_PROTOCOL',
        description: 'Execution of decree or initiation of appellate proceedings',
        completed: false,
      },
    ],
  },
  rera: {
    name: 'RERA_PROCEEDING',
    description: 'Regulatory complaint under Real Estate Authority framework',
    steps: [
      {
        id: 1,
        label: 'DOCUMENT_ARCHIVAL',
        description: 'Collection of agreement, payment receipts, and RERA registration markers',
        completed: false,
      },
      {
        id: 2,
        label: 'NOTICE_TO_DEVELOPER',
        description: 'Issuance of formal statutory notice for deficiency or delay',
        completed: false,
        expectedDays: 30,
      },
      {
        id: 3,
        label: 'FILE_RERA_COMPLAINT',
        description: 'Formal submission of complaint at the State RERA Authority portal',
        completed: false,
      },
      { id: 4, label: 'FILING_FEE_SETTLEMENT', description: 'Settlement of mandated Rs. 5,000 regulatory fee', completed: false },
      {
        id: 5,
        label: 'ADMISSION_HEARING',
        description: 'First listing and admission hearing by RERA Authority',
        completed: false,
      },
      {
        id: 6,
        label: 'REPLY_BY_DEVELOPER',
        description: 'Developer party files formal reply or procedural objections',
        completed: false,
      },
      {
        id: 7,
        label: 'EVIDENTIARY_HEARING',
        description: 'Presentation of verified evidence and final arguments',
        completed: false,
      },
      {
        id: 8,
        label: 'REGULATORY_ORDER',
        description: 'Receipt of formal order for refund or statutory compensation',
        completed: false,
      },
    ],
  },
  chequebounce: {
    name: 'NI_ACT_SECTION_138',
    description: 'Negotiable Instruments Act procedural timeline',
    steps: [
      {
        id: 1,
        label: 'CHEQUE_DISHONOR',
        description: 'Issuance of bank return memo marking cheque dishonor',
        completed: false,
      },
      {
        id: 2,
        label: 'STATUTORY_DEMAND_NOTICE',
        description: 'Issuance of demand notice within 30 days of dishonor',
        completed: false,
        expectedDays: 30,
      },
      {
        id: 3,
        label: 'COOLING_OFF_PERIOD',
        description: 'Mandated 15-day waiting period for payment post-notice',
        completed: false,
        expectedDays: 15,
      },
      {
        id: 4,
        label: 'FILING_OF_COMPLAINT',
        description: 'Formal filing of criminal complaint under Section 138 of NI Act',
        completed: false,
      },
      {
        id: 5,
        label: 'SUMMONS_ISSUANCE',
        description: 'Judicial issuance of summons to the accused party',
        completed: false,
      },
      {
        id: 6,
        label: 'JUDICIAL_APPEARANCE',
        description: 'Appearance of accused and filing of formal reply',
        completed: false,
      },
      {
        id: 7,
        label: 'EVIDENTIARY_PHASE',
        description: 'Submission of original memo, notice, and service proof',
        completed: false,
      },
      { id: 8, label: 'FINAL_ARGUMENTS', description: 'Submission of arguments for conviction', completed: false },
      { id: 9, label: 'FINAL_ADJUDICATION', description: 'Judicial pronouncement of verdict', completed: false },
      {
        id: 10,
        label: 'COMPENSATION_EXECUTION',
        description: 'Receipt of compensation or filing of appellate proceeding',
        completed: false,
      },
    ],
  },
  family: {
    name: 'MATRIMONIAL_STATUTORY_CONTEST',
    description: 'Statutory proceedings under Personal Laws and Family Court framework',
    steps: [
      {
        id: 1,
        label: 'Consultation & Strategy',
        description: 'Discuss grounds, relief sought, and evidence',
        completed: false,
      },
      {
        id: 2,
        label: 'Send Notice / Attempt Mediation',
        description: 'Legal notice or mutual consent approach',
        completed: false,
      },
      {
        id: 3,
        label: 'File Petition',
        description: 'File at Family Court (divorce/maintenance/custody)',
        completed: false,
      },
      {
        id: 4,
        label: 'First Motion',
        description: 'First motion hearing and statements',
        completed: false,
      },
      {
        id: 5,
        label: 'Mediation / Counseling',
        description: 'Court refers to mediation center',
        completed: false,
      },
      {
        id: 6,
        label: 'Evidence (if contested)',
        description: 'Present evidence and witnesses',
        completed: false,
      },
      { id: 7, label: 'Final Arguments', description: 'Present final arguments', completed: false },
      { id: 8, label: 'Decree / Order', description: 'Receive court order', completed: false },
    ],
  },
  custom: {
    name: 'AUTONOMOUS_STATUTORY_TRACE',
    description: 'Create a custom procedural timeline',
    steps: [
      {
        id: 1,
        label: 'Initial Research',
        description: 'Understand your legal position',
        completed: false,
      },
      {
        id: 2,
        label: 'Gather Documents',
        description: 'Collect all relevant documents',
        completed: false,
      },
      {
        id: 3,
        label: 'Consult Lawyer',
        description: 'Get professional legal advice',
        completed: false,
      },
      { id: 4, label: 'Take Action', description: 'File case or send notice', completed: false },
    ],
  },
};
