import jsPDF from 'jspdf';

export function downloadDocumentPDF(documentText, templateTitle) {
  const doc = new jsPDF();

  // 1. Typography must look like a legal document
  doc.setFont('times', 'normal');

  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // 2. Add a header and footer to every page
  const addHeaderFooter = (pageNum) => {
    // Header
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      'Generated by JusticeAI \u2014 For Reference Purposes Only',
      pageWidth - margin,
      15,
      { align: 'right' },
    );

    // Footer
    doc.text(
      `Page ${pageNum}  |  Generated on: ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' },
    );
  };

  let cursorY = margin + 10;
  let pageNum = 1;

  addHeaderFooter(pageNum);

  // Body Setup
  doc.setFontSize(12);
  doc.setTextColor(0);

  // Auto-paginating text splitting
  const lines = doc.splitTextToSize(documentText, maxWidth);

  lines.forEach((line) => {
    if (cursorY > pageHeight - margin - 20) {
      doc.addPage();
      pageNum++;
      addHeaderFooter(pageNum);
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.setFont('times', 'normal');
      cursorY = margin + 10;
    }
    doc.text(line, margin, cursorY);
    cursorY += 6;
  });

  // 3. Add the disclaimer as the last line of every document
  cursorY += 10;
  if (cursorY > pageHeight - margin - 20) {
    doc.addPage();
    pageNum++;
    addHeaderFooter(pageNum);
    cursorY = margin + 10;
  }

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont('times', 'italic');
  const disclaimer =
    'This document is a template generated for informational purposes. It has not been reviewed by a licensed advocate. Do not submit to any court or authority without professional legal review.';
  const disclaimerLines = doc.splitTextToSize(disclaimer, maxWidth);

  disclaimerLines.forEach((line) => {
    doc.text(line, margin, cursorY);
    cursorY += 5;
  });

  // 4. Filename should be descriptive
  const dateStr = new Date().toISOString().split('T')[0];
  const filename = `JusticeAI_${templateTitle.replace(/\s+/g, '')}_${dateStr}.pdf`;

  doc.save(filename);
}
